[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'traderev'
version = '0.0.1'
license = {file = "LICENSE.txt"}
dependencies = [
    'Flask',
    'Flask-PyMongo',
    'pandas'
]